apiVersion: apps/v1
kind: Deployment
metadata:
  name: gataria-backend-iamges
  labels:
    app: gataria-backend-images
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gataria-backend-images
  template:
    metadata:
      labels:
        app: gataria-backend-images
    spec:
      containers:
      - name: gataria-backend-catalog
        image: williammedeiros007/gataria-backend-images:v1
        ports:
        - containerPort: 3020
        env:
        - name: CATAPI_URL
          valueFrom:
            configMapKeyRef:
              name: gataria-envs
              key: CATAPI_URL